### ISSUE TITLE
Why can't get exact amounts of result?

### ISSUE THREAD

**Issue by Alisaincd** [kayzhu/LSHash#19]
Hi, I set 'r = lsh.query(inputs[200], distance_func='hamming', num_results=20)', in which the number of returned results is 20, but sometimes I just got only one result(or less than 20 items) .Can you tell me the reason? Or how should I fixed it?
Thanks a lot,
Sincerely

**Comment by geovedi** [comment]
it's known problem in LSH in general where closed items can have different hashes, thus reflecting the query result. another issue might be the generated uniform planes doesn't reflect your data distribution.

**Comment by Alisaincd** [comment]
Hi, thank you very much! By the way ,can you share the paper links that related to this project? I want to study it furthermore.

**Comment by AnuradhaSK** [comment]
@Alisaincd Could you fix it?
